### ISSUE TITLE
Icon remains in system tray after exiting

### ISSUE THREAD

**Issue by shieox101** [xNetrunner/NWNLogRotator#15]
Icon remains in system tray after exiting, only disappears from the system tray if the mouse cursor is moved over it.

**Comment by xNetrunner** [comment]
I just tested it inside of a VM and I can't get it to break.

But I don't know if it broke there before. If it's not working, I'd ask how you are closing this app? Is it forcefully via a script or something?

**Comment by shieox101** [comment]
> Yes the fix is not working unfortunately. I am using the silent/tray/run client/direct connect and close on log generated options.

**Comment by xNetrunner** [comment]
okay, here's the latest
[NWNLogRotator.zip](https://github.com/xNetrunner/NWNLogRotator/files/11377311/NWNLogRotator.zip)

**Comment by shieox101** [comment]
> 

That definitely works and fixed the issue for me on Windows 10, thanks!
